# Generated by Django 4.2.30 on 2026-09-17 13:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Kategori Adı')),
            ],
        ),
        migrations.CreateModel(
            name='Leaderboard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=50, verbose_name='Kullanıcı Adı')),
                ('score', models.IntegerField(verbose_name='Skor')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Oynanma Tarihi')),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(verbose_name='Soru Metni')),
                ('option_a', models.CharField(max_length=255, verbose_name='A Seçeneği')),
                ('option_b', models.CharField(max_length=255, verbose_name='B Seçeneği')),
                ('option_c', models.CharField(max_length=255, verbose_name='C Seçeneği')),
                ('option_d', models.CharField(max_length=255, verbose_name='D Seçeneği')),
                ('correct_option', models.CharField(choices=[('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D')], max_length=1, verbose_name='Doğru Cevap')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='quiz.category')),
            ],
        ),
    ]
