# Generated by Django 4.2.30 on 2026-09-17 14:15

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='GameSession',
            fields=[
                ('session_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('start_time', models.DateTimeField(auto_now_add=True, verbose_name='Başlangıç Zamanı')),
                ('current_score', models.IntegerField(default=0, verbose_name='Güncel Skor')),
                ('is_active', models.BooleanField(default=True, verbose_name='Aktif Mi?')),
            ],
        ),
    ]
