# Generated by Django 4.2.30 on 2026-09-17 20:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0002_gamesession'),
    ]

    operations = [
        migrations.AddField(
            model_name='gamesession',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='quiz.category', verbose_name='Seçilen Kategori'),
        ),
        migrations.AddField(
            model_name='leaderboard',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='quiz.category', verbose_name='Kategori'),
        ),
    ]
