# Generated by Django 4.2.30 on 2026-09-17 22:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0003_gamesession_category_leaderboard_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='GameSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('max_home_categories', models.IntegerField(default=4, verbose_name='Ana Sayfa Maksimum Kategori Sayısı')),
                ('daily_challenge_duration_days', models.IntegerField(default=1, verbose_name='Günün Kategorisi Süresi (Gün)')),
            ],
            options={
                'verbose_name': 'Oyun Ayarları',
                'verbose_name_plural': 'Oyun Ayarları',
            },
        ),
        migrations.AddField(
            model_name='category',
            name='daily_challenge_date',
            field=models.DateField(blank=True, null=True, verbose_name='Günün Kategorisi Olma Tarihi'),
        ),
        migrations.AddField(
            model_name='category',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Aktif Mi?'),
        ),
        migrations.AddField(
            model_name='category',
            name='is_daily_challenge',
            field=models.BooleanField(default=False, verbose_name='Günün Kategorisi Mi?'),
        ),
        migrations.CreateModel(
            name='DailyQuestionCache',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now_add=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quiz.category')),
                ('questions', models.ManyToManyField(to='quiz.question')),
            ],
        ),
    ]
