# Generated by Django 4.2.30 on 2026-09-18 10:10

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0004_gamesettings_category_daily_challenge_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='gamesettings',
            name='daily_reset_time',
            field=models.TimeField(default=datetime.time(0, 0), verbose_name='Günlük Soruların Yenilenme Saati'),
        ),
    ]
